### ISSUE TITLE
Template Bootstrap

### ISSUE THREAD

**Issue by leomoille** [leomoille/leomoilledotcom#1]
## Todo
- [x] Choisir un template Bootstrap
- [x] Intégrer le template (voir #2 )

## Informations
- Le template est [disponible ici](https://github.com/StartBootstrap/startbootstrap-clean-blog)
- Le template utilise la version 5 de Bootstrap ♥
- Utilisation de Twig comme moteur de template

**Comment by leomoille** [comment]
### Todo
- [ ] Choisir un template Bootstrap
- [ ] Intégrer le template
